drhagen/parsita

src/parsita/__init__.py, src/parsita/parsers.py, src/parsita/state.py, tests/test_basic.py, tests/test_regex.py
=> added until parser

.github/workflows/python.yml, poetry.lock, pyproject.toml
Also remove Poetry from the pyproject.toml file as that is not needed.
=> Update to Poetry 1.2.0

poetry.lock
=> Update Poetry lock file

examples/positioned.py, pyproject.toml, src/parsita/parsers.py, src/parsita/state.py, tests/test_regex.py, tests/test_state.py
=> Switch to packrat parser

docs/contributing.md
This fixes some outdated information on the `contributing.md` page.
=> Update contributing docs

src/parsita/__init__.py, src/parsita/parsers.py, src/parsita/state.py, tests/test_basic.py, tests/test_regex.py, tests/test_state.py
Also turn SequenceReader and StringReader into dataclasses.
=> Create custom recursion error

poetry.lock, pyproject.toml
This just brings all dependencies up to their latest major versions.
=> Bump all dependency versions

docs/getting_started.md
=> Fix regex in getting_started.md

src/parsita/parsers.py, src/parsita/state.py, tests/test_basic.py, tests/test_state.py
=> Allow reg in GeneralParsers context

README.md, docs/alternative_parsers.md, docs/conversion_parsers.md, docs/getting_started.md, docs/index.md, docs/miscellaneous_parsers.md, docs/repeated_parsers.md, docs/sequential_parsers.md, docs/terminal_parsers.md, docs/utility_functions.md, examples/expressions.py, examples/json.py, examples/positioned.py, examples/url.py, src/parsita/__init__.py, src/parsita/metaclasses.py, tests/test_basic.py, tests/test_metaclass_scopes.py, tests/test_regex.py
=> Combine GeneralParsers and TextParsers into ParserContext

.github/workflows/ci.yml, poetry.lock
The last tag push did not trigger GitHub Actions. I am not sure how it ever worked before because tags was definitely missing from the workflow triggers.
=> Run CI on tags

docs/contributing.md, docs/conversion_parsers.md, docs/getting_started.md, docs/terminal_parsers.md
I read through the docs looking for any minor improvements to be made before 2.0 is released.
=> Minor fixes to docs

examples/json.py, examples/url.py, pyproject.toml, src/parsita/__init__.py, src/parsita/metaclasses.py, src/parsita/parsers/__init__.py, src/parsita/parsers/_alternative.py, src/parsita/parsers/_any.py, src/parsita/parsers/_base.py, src/parsita/parsers/_conversion.py, src/parsita/parsers/_end_of_source.py, src/parsita/parsers/_predicate.py, src/parsita/parsers/_repeated.py, src/parsita/parsers/_repeated_seperated.py, src/parsita/parsers/_sequential.py, src/parsita/state/_reader.py, src/parsita/util.py, tests/test_basic.py, tests/test_examples.py, tests/test_regex.py, tests/test_state.py
This is to be consistent with the [Python blueprint](https://github.com/johnthagen/python-blueprint).
=> Change line length to 99

docs/contributing.md
Add instructions to Contributing page on how to manually publish the package to conda-forge.
=> Add conda forge instructions

poetry.lock, pyproject.toml
Also update to nox-poetry 1.0.3 to eliminate warning.
=> Add support for Returns 0.21

.github/workflows/ci.yml, noxfile.py, poetry.lock, pyproject.toml
* Add support for Returns 0.22
* Upgrade to pytest 7.4
=> Add Python 3.12 support

docs/alternative_parsers.md, docs/contributing.md, docs/conversion_parsers.md, docs/getting_started.md, docs/index.md, docs/miscellaneous_parsers.md, docs/repeated_parsers.md, docs/sequential_parsers.md, docs/terminal_parsers.md, docs/utility_functions.md, mkdocs.yml
=> Make theme match system theme

.github/workflows/ci.yml, .github/workflows/release.yml, pyproject.toml
* Add trove classifier for Python 3.13
* Bump Poetry version in CI
* Bump Ubuntu version in CI
=> Cleanup build

.github/workflows/ci.yml, .github/workflows/release.yml, pyproject.toml
Poetry 1.8.4 added full support for Python 3.13.
=> Remove Poetry workaround for Python 3.13

.github/workflows/ci.yml, docs/contributing.md
- Use only Nox group when testing in CI
- Fix error in docs
=> Minor fixes
