drhagen/parsita

- tox.ini
From recommendation here: https://github.com/codecov/example-python#testing-with-tox
> Simplify tox passenv

- src/parsita/options.py
- src/parsita/parsers.py
- src/parsita/state.py
- src/parsita/util.py
- tests/test_state.py
While I’m going to expand that other pull request tomorrow, I’ve already compiled here some fixes (or misunderstandings :grin:), if you’d like. (At first I tried to make mypy happy, but that doesn’t seem reasonable at the moment.) I’ll be glad to leave only those you consider correct.
options.py:
* `wrap_literal`: `LiteralParser` expected a sequence of Inputs
parsers.py:
* `*parsers` arguments’ types now conform with PEP 484 <https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values>
* minor fixes (if I’m not wrong)
state.py:
* an assertion in using a regex match, in case it would be None for some reason
* minor fixes in several type hints
util.py:
* PEP 484 advices the first `TypeVar` argument be the same as the var name. That probably was a typo
> Several small fixes:

- README.rst
- src/parsita/__init__.py
- src/parsita/parsers.py
- tests/test_basic.py
- tests/test_regex.py
This one adds a predicate parser, which is useful to match a general input literal partially, like matching a token by its type but not all other info which a token has.
Simple tests are included (I used the literal parser test case as a reference), and are passing.
What do you think? :slightly_smiling_face:
> Add a predicate parser

- src/parsita/parsers.py
- src/parsita/state.py
- tests/test_basic.py
- tests/test_regex.py
- tests/test_state.py
Convert `ParseError` to a dataclass that holds the parsing state. The message is moved to the `__str__` method of the error.
Implements #39.
> Convert ParseError to a dataclass with state

- docs/alternative_parsers.md
- docs/miscellaneous_parsers.md
- src/parsita/parsers/__init__.py
- src/parsita/parsers/_alternative.py
- src/parsita/parsers/_base.py
- src/parsita/parsers/_literal.py
- tests/test_basic.py
- tests/test_regex.py
This is in accordance with the long standing to make the default behavior more user-friendly.
Closes #55.
> Make longest the default for the | operator

- pyproject.toml
- src/parsita/parsers/_regex.py
- tests/test_basic.py
This used to be enabled when we used flake8, but was lost in the migration to Ruff.
> Enable W on ruff

- pyproject.toml
This is a [better solution](https://github.com/johnthagen/python-blueprint/pull/178) than pycodestyle warnings for detecting invalid escape sequences.
> Activate strict pytest options

- src/parsita/metaclasses.py
- src/parsita/options.py
- src/parsita/parsers/__init__.py
- src/parsita/parsers/_base.py
- tests/test_basic.py
Inspired by #77, I found that removing the `parse_method` global mutable state is relatively straightforward. It can be replaced by a switch that chooses the `Reader` subtype based on the input type. All the readers seem to work in all contexts, so this is a change that dramatically reduces the complexity of the context system.
This changes the error messages when parsing `str` input in a `GeneralParsers` context, but that seems like a good thing overall.
> Remove context-specific parse

- src/parsita/metaclasses.py
- src/parsita/options.py
- src/parsita/parsers/__init__.py
- src/parsita/parsers/_base.py
- src/parsita/parsers/_literal.py
- src/parsita/parsers/_regex.py
- tests/test_basic.py
* Behavior on lit now independent of context
* LiteralParser and LiteralStringParser have been combined
* lit is specialized to generate nice text error messages on StringReader
* Removed global mutable state for lit
* GeneralParsers now responds to whitespace and TextParsers inherits this behavior
* default_whitespace moved to context class attribute
* reg now takes Pattern or str
* RegexParser now takes Pattern only
> Remove context-specific lit

- src/parsita/__init__.py
- src/parsita/metaclasses.py
- tests/test_regex.py
- tests/test_state.py
Backport of #81
This should allow `ParserContext` to be used in a forward-compatible manner in v1.
> Backport ParserContext

- src/parsita/metaclasses.py
- src/parsita/state.py
This is a follow on to #82 to mark the old parser contexts as deprecated.
> Mark GeneralParsers and TextParsers as deprecated

- src/parsita/metaclasses.py
- src/parsita/state.py
The stacklevel on the parser contexts were not right and the state was using deprecated attributes internally.
> Improve deprecation reporting

- src/parsita/parsers/_predicate.py
- tests/test_basic.py
- tests/test_regex.py
Fixes #86 by simply moving the error to the end of successfully parsed content.
> Move predicate parser error to end of parsed content

- src/parsita/state/_reader.py
- tests/test_regex.py
- tests/test_state.py
I often wish that the line and error location was visible even when at the end of the source.
> Show error location even at end of source

- examples/positioned.py
- src/parsita/parsers/__init__.py
- src/parsita/parsers/_alternative.py
- src/parsita/parsers/_any.py
- src/parsita/parsers/_base.py
- src/parsita/parsers/_conversion.py
- src/parsita/parsers/_debug.py
- src/parsita/parsers/_end_of_source.py
- src/parsita/parsers/_literal.py
- src/parsita/parsers/_optional.py
- src/parsita/parsers/_predicate.py
- src/parsita/parsers/_regex.py
- src/parsita/parsers/_repeated.py
- src/parsita/parsers/_repeated_seperated.py
- src/parsita/parsers/_sequential.py
- src/parsita/parsers/_success.py
- src/parsita/parsers/_until.py
- src/parsita/state/_reader.py
Partially implements #95.
- Rename `StringReader.current_line` to `_current_line`
- Extract `handle_other` to global function
- Rename `handle_other` to `wrap_literal`
- Use `wrap_literal` in all parsers
- `PredicateParser` was not wrapping literals at all, now is
- Most parsers only wrapped `str`, now all wrap non-`Parser`s
- Rename `consume` to `_consume`
- Rename `cached_consume` to `consume`
> Make various methods private

- README.md
Poetry now has an official badge. Add it to the README to make its usage more visible to users.
- https://python-poetry.org/blog/announcing-poetry-1.6.0/#official-poetry-badge
> Add official Poetry badge

- .github/workflows/ci.yml
- .github/workflows/release.yml
- docs/contributing.md
- pyproject.toml
With 2FA about to be made mandatory on PyPI, this uses the blessed `pypa/gh-action-pypi-publish` GitHub action to publish a new version to PyPI whenever a new tag is pushed.
> Create automatic releases from tags

- .github/workflows/ci.yml
- docs/contributing.md
- noxfile.py
- poetry.lock
- pyproject.toml
- src/parsita/metaclasses.py
- src/parsita/parsers/_literal.py
- src/parsita/parsers/_repeated.py
Ruff now implements the `black` formatter as the `ruff format` command. Given that we already use Ruff, switching to this makes sense.
> Switch formatter to Ruff

- examples/expressions.py
- examples/json.py
- examples/positioned.py
- examples/url.py
- poetry.lock
- pyproject.toml
- src/parsita/parsers/_base.py
- src/parsita/state/_exceptions.py
- src/parsita/state/_state.py
* Replace format with f-strings
* Use builtin generics
* Update to Ruff 0.6
> Update to supported Python features

- src/parsita/parsers/_conversion.py
- src/parsita/parsers/_regex.py
- tests/test_basic.py
- tests/test_regex.py
The reprs of several parsers were not accurate. This fixes them.
- TransformationParser
- ConversionParser
- RegexParser
> Fix string representations of parsers

- examples/url.py
- noxfile.py
- pyproject.toml
- src/parsita/__init__.py
- src/parsita/parsers/__init__.py
- src/parsita/state/__init__.py
Resolves #118.
This is ugly and should be undone as soon as an alternative is available.
> Re-export all public members for mypy

- src/parsita/metaclasses.py
- tests/test_basic.py
I've tried adding type annotations to parser and I was getting
```
TypeError: 'ForwardDeclaration' object does not support item assignment
```
This PR fixes it by ignoring annotations, which is likely wrong. I'd be happy to improve the solution.
> Handle type annotations

- README.md
The build status link needs to follow the job `name`, not its file name:
https://github.com/drhagen/parsita/blob/6182b488dd0ba2f4db5cacef7d49e8ddb1439125/.github/workflows/ci.yml#L1
> Fix CI build status image
